import { ROUTE_PATH } from 'consts';

export const breadcrumbNameMap = {
  '/news': 'Tin tức',
  '/setting': 'Cài đặt',
  '/setting/intro-page': 'Trang giới thiệu',
  '/setting/config-first-login': 'Cấu hình lần đầu đăng nhập',
  '/setting/faq-topic': 'Cấu hình FAQ- Chủ đề',
  '/setting/faq-question': 'Cấu hình FAQ- Câu hỏi',
  '/setting/terms-of-use': 'Điều khoản sử dụng',
  '/setting/contact-info': 'Thông tin liên hệ',
  '/setting/banner': 'Cấu hình banner',
  //-------Quản lý hoạt động học tập--------
  '/learning': 'Quản lý hoạt động học tập',
  '/learning/courses': 'Khóa học',
  '/learning/program-code': 'Mã chương trình ',
  '/learning/category-training': 'Hạng mục đào tạo',
  '/learning/courses/new': 'Tạo khóa học mới',
  '/learning/courses-overview': 'Tổng quan khóa học',
  '/learning/user-assigned': 'Danh sách học viên đã gán',
  [ROUTE_PATH.LESSON_STRUCTURE]: 'Cấu trúc bài học',
  [ROUTE_PATH.LESSON_CONTENT_ADD]: 'Thêm nội dung bài học',
  [ROUTE_PATH.LESSON_CONTENT_UPDATE]: 'Chỉnh sửa nội dung bài học',
  [ROUTE_PATH.ACTIVATION_SETTING]: 'Kích hoạt và thiết lập',
  [ROUTE_PATH.APPROVAL_COURSE]: 'Cấu hình luồng phê duyệt',
  [ROUTE_PATH.APPROVAL_LIST]: 'Danh sách phê duyệt',
  //-------Content--------
  '/content': 'Nội dung',
  [ROUTE_PATH.SURVEY]: 'Khảo sát',
  [ROUTE_PATH.SURVEY_ADD]: 'Tạo khảo sát',
  [ROUTE_PATH.SURVEY_UPDATE]: 'Chỉnh sửa khảo sát',
  [ROUTE_PATH.SURVEY_DETAIL]: 'Chi tiết khảo sát',
  [ROUTE_PATH.IMPORT_CONTENT]: 'Import nội dung',
  [ROUTE_PATH.IMPORT_CONTENT_ADD]: 'Thêm nội dung mới',
  [ROUTE_PATH.IMPORT_CONTENT_UPDATE]: 'Chỉnh sửa nội dung',
  // [ROUTE_PATH.IMPORT_CONTENT_DETAIL]: 'Chi tiết khảo sát',
  [ROUTE_PATH.QUESTION_BANK]: 'Ngân hàng câu hỏi',
  [ROUTE_PATH.QUESTION_BANK_UPDATE]: 'Chỉnh sửa câu hỏi',
  [ROUTE_PATH.QUESTION_BANK_DETAIL]: 'Chi tiết câu hỏi',
  [ROUTE_PATH.QUESTION_BANK_ADD]: 'Tạo mới câu hỏi',
  [ROUTE_PATH.EXAMINATION]: 'Bài kiểm tra',
  [ROUTE_PATH.EXAMINATION_ADD]: 'Tạo bài kiểm tra',
  [ROUTE_PATH.EXAMINATION_UPDATE]: 'Chỉnh sửa bài kiểm tra',
  [ROUTE_PATH.EXAMINATION_DETAIL]: 'Tổng quan bài kiểm tra',
  [ROUTE_PATH.PREVIEW_COURSE]: 'Xem trước tổng quan khoá học',
  //-------Quản lý hoạt động đào tạo--------
  '/training': 'Quản lý hoạt động đào tạo',
  [ROUTE_PATH.ASSIGN_COURSE]: 'Gán/Huỷ khoá học',
  [ROUTE_PATH.COURSE_DETAIL]: 'Chi tiết khóa học'
};
